### ISSUE TITLE
Implementar armadilhas

### ISSUE THREAD

**Issue by EltonCN** [EltonCN/MC322-Projeto#32]
Devem existir armadilhas escondidas em que os heróis caem nela, perdendo um de vida e mostrando na tela

- [x] Criar a classe herdando HeroQuest. Não movível, não atacável, porém atacante

- [x] Criar interação com o jogador de acionamento- usar SimpleAttack

- [x] Possibilitar desativação

- [x] Ajustar draw() - só funciona quando ela for detectada

**Comment by Lucas-Otavio** [comment]
Foi feita refatoração ao invés de usar SimpleAttack
Armadilhas estão atacando vizinhos, estão intransponíveis
