### ISSUE TITLE
Implementar procura por tesouros

### ISSUE THREAD

**Issue by EltonCN** [EltonCN/MC322-Projeto#33]
>O herói deve ser capaz de procurar por tesouros (tem uma chance de encontrar um monstro);

Entidade que representa um tesouro, é invisível até ser detectada. É transponível

- [x] Criar classe herdando HeroQuestEntity - interagível

- [x] Criar interação, que fornece moedas de ouro

**Comment by Lucas-Otavio** [comment]
Plus: Moedas de ouro viram money
