### ISSUE TITLE
Implementar RandomChaseMovement

### ISSUE THREAD

**Issue by EltonCN** [EltonCN/MC322-Projeto#40]
Criar um movimento que alterna entre Random quando está longe de jogadores, e Chase quando está próximo. Usar herança de Random e composição com Chase

**Comment by Lucas-Otavio** [comment]
Feito. Precisei inverter, pois métodos antes privados de ChaseMovement eram necessários. Então tornei os métodos protegidos e fiz extensão de ChaseMovement com composição de RandomMovement
